---

- name: Include check.yml
  ansible.builtin.include_tasks: check.yml
  when: docker_compose_type is search('^(pip|binary|both)$')

- name: Include binary.yml
  ansible.builtin.include_tasks: binary.yml
  when: docker_compose_type is search('^(binary|both)$')

- name: Include pip.yml
  ansible.builtin.include_tasks: pip.yml
  when:
    - docker_compose_type is search('^(pip|both)$')
    - not docker_compose_pipinvenv | bool

- name: Include pip-venv.yml
  ansible.builtin.include_tasks: pip-venv.yml
  when:
    - docker_compose_type is search('^(pip|both)$')
    - docker_compose_pipinvenv | bool

- name: Include template.yml
  ansible.builtin.include_tasks: template.yml
  when: docker_compose_template_file is defined
