---

- name: Install docker-compose via pip
  ansible.builtin.pip:
    name: docker-compose
    state: present
  environment:
    HTTPS_PROXY: "{{ python_https_proxy | default('') }}"
    HTTP_PROXY: "{{ python_http_proxy | default('') }}"
  tags: molecule-idempotence-notest
