---

- name: Assertions
  ansible.builtin.assert:
    that:
      - docker_compose_project_name is defined
      - docker_compose_template_file is defined

- name: Read docker-compose settings from template
  ansible.builtin.set_fact:
    docker_compose_template: >-
      {{ lookup('template', docker_compose_template_file) | from_yaml }}

- name: Get all files/directories to map
  ansible.builtin.set_fact:
    volume_paths: >-
      {{ docker_compose_template['services'] |
         dict2items |
         json_query('[].value.volumes') |
         json_query('[]') |
         select('regex', '^(\./|/)') |
         map('regex_replace', ':.*') |
         list }}

- name: Make sure no relative paths are used
  ansible.builtin.fail:
    msg: "Relative paths in volume names!"
  when: volume_paths is search('^\./')

- name: Get status of all these files/directories
  ansible.builtin.stat:
    path: "{{ path }}"
  become: "{{ docker_compose_become }}"
  loop: "{{ volume_paths }}"
  loop_control:
    loop_var: path
  register: __stat

- name: Create the main project directory
  ansible.builtin.file:
    path: "{{ docker_compose_project_dir }}"
    state: directory
    owner: "{{ 'root' if (docker_compose_become | bool) else omit }}"
    group: "{{ (docker_group | default('root')) if (docker_compose_become | bool) else omit }}"
    mode: "{{ docker_compose_mode | default('0750') }}"
  become: "{{ docker_compose_become }}"

- name: Create directories that do not exist
  ansible.builtin.file:
    path: "{{ volume_path.path }}"
    state: directory
    owner: "{{ docker_compose_owner | default('root') }}"
    group: "{{ docker_compose_group | default(docker_group) | default('root') }}"
    mode: "{{ docker_compose_mode | default('0750') }}"
  become: "{{ docker_compose_become }}"
  loop: "{{ __stat.results }}"
  loop_control:
    loop_var: volume_path
    label: "{{ volume_path.path }}"
  when: not volume_path.stat.exists or volume_path.stat.isdir

- name: Create files from template
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  become: "{{ docker_compose_become }}"
  loop: "{{ docker_compose_files | default([]) }}"
  register: __dc1

- name: Create docker-compose.yml from template
  ansible.builtin.template:
    src: "{{ docker_compose_template_file }}"
    dest: "{{ docker_compose_project_dir }}/docker-compose.yml"
    mode: "0644"
  become: "{{ docker_compose_become }}"
  register: __dc2

- name: Restart the project  # noqa no-handler
  become: "{{ docker_compose_become }}"
  when: docker_compose_restart | bool or __dc1.changed or __dc2.changed
  block:

    - name: Stop the docker-compose project
      community.docker.docker_compose:
        state: absent
        project_src: "{{ docker_compose_project_dir }}"

    - name: Initialize docker-compose project
      community.docker.docker_compose:
        state: present
        project_src: "{{ docker_compose_project_dir }}"
        build: false
        pull: "{{ docker_compose_pull }}"
