---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    python_package_install_optional: True
    docker_compose_type: pip
  roles:
    - deitkrachten.python
  tasks:
    - name: Include role 'ansible-role-docker_compose'
      ansible.builtin.include_role:
        name: ansible-role-docker_compose
